# MyPlugin by Fuglen - Default config.yml #
 
# Do you want your players to recieve a message when they join the server?
Welcome Players: true
 
# Custom message for your players. %player% will be the players name.
Welcome Message: '&2Welcome back %player%!'