name: MyPlugin
version: 1.1.0
description: Made by Fuglen
author: Fuglen
main: me.Fuglen.myplugin.MyPlugin
#website: https://github.com/Fuglen/MyPlugin
 
commands:
    fly:
      description: Se hvad du kan med /fly.
      usage: /<command>
    fire:
      description: Sæt ild til en spiller!
      usage: /<command>
    time:
      description: ændre tiden til dag eller nat.
      usage: /<command>
    vejr:
      description: ændre vejret til sol, regn eller storm.
      usage: /<command>

#ALL PERMISSIONS
permissions:
    myplugin.*:
        description: Gives acccess to all commands
        children:
            myplugin.fire.*: true
            myplugin.fly.*: true
        
    #Permissions for /fire
    myplugin.fire.*:
        description: Gives access to all fire commands
        children:
            myplugin.fire: true
            myplugin.fire.others: true
            
    myplugin.fire:
        description: Set yourself on fire
        default: false
    myplugin.fire.others:
        description: Set other players on fire
        default: false
        
    #Permissions for /fly
    myplugin.fly.*:
        description: Gives access to all fly commands
        children:
            myplugin.fly: true
            myplugin.fly.others: true
            
    myplugin.fly:
        description: Gives yourself the ability to fly
        default: true
    myplugin.fly.others:
        description: Gives another player the ability to fly
        default: false
    
    #Permissions for /vejr
    myplugin.weather.*:
        description: Gives access to all weather commands
        children:
            myplugin.weather.sun: true
            myplugin.weather.rain: true
            myplugin.weather.thunder: true
            myplugin.weather.clear: true

    myplugin.weather.sun:
        description: Gives you access to change the weather to sunshine.
        default: true
    myplugin.weather.rain:
        description: Gives you access to change the weather to rain.
        default: false
    myplugin.weather.thunder:
        description: Gives you access to change the weather to thunder.
        default: true
    myplugin.weather.clear:
        description: Gives you access to change the weathert to thunder.
        default: false
    
    #Permissions for /time
    myplugin.time.*:
        description: Gives access to all time commands.
        children:
            myplugin.time.day: true
            myplugin.time.night: true

    myplugin.time.day:
        description: Gives you access to change the time to day.
        default: true
    myplugin.time.night:
        description: Gives you access to change the time to night.
        default: false
        
    #Permissions for the join event
    myplugin.join.*:
        description: Gives you access to everything with the join event.
        children:
            myplugin.join.message: true
    
    myplugin.join.message:
        description: Gives you access to recieve an message when you join the server.
        default: true
        